# Generated by Django 4.1.2 on 2022-10-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "priority",
                    models.CharField(
                        choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("TD", "To Do"),
                            ("IP", "In Progress"),
                            ("DN", "Done"),
                        ],
                        default="TD",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
